# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/ip/triangular_rom256x8/triangular_rom256x8.xci
# IP: The module: 'triangular_rom256x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/ip/triangular_rom256x8/triangular_rom256x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'triangular_rom256x8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/ip/triangular_rom256x8/triangular_rom256x8.xci
# IP: The module: 'triangular_rom256x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/ip/triangular_rom256x8/triangular_rom256x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'triangular_rom256x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
