# 
# Synthesis run script generated by Vivado
# 

set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Verilogshuzixitongzonghesheji/DDS/DDS.cache/wt [current_project]
set_property parent.project_path D:/Verilogshuzixitongzonghesheji/DDS/DDS.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Verilogshuzixitongzonghesheji/DDS/DDS.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/ip/triangular_rom256x8/triangular_rom256x8.xci
set_property used_in_implementation false [get_files -all d:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/ip/triangular_rom256x8/triangular_rom256x8_ooc.xdc]
set_property is_locked true [get_files D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/ip/triangular_rom256x8/triangular_rom256x8.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir D:/Verilogshuzixitongzonghesheji/DDS/DDS.runs/triangular_rom256x8_synth_1 -new_name triangular_rom256x8 -ip [get_ips triangular_rom256x8]]

if { $cached_ip eq {} } {

synth_design -top triangular_rom256x8 -part xc7a35tcsg324-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
catch {
 write_checkpoint -force -noxdef -rename_prefix triangular_rom256x8_ triangular_rom256x8.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ triangular_rom256x8_stub.v
 lappend ipCachedFiles triangular_rom256x8_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ triangular_rom256x8_stub.vhdl
 lappend ipCachedFiles triangular_rom256x8_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ triangular_rom256x8_sim_netlist.v
 lappend ipCachedFiles triangular_rom256x8_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ triangular_rom256x8_sim_netlist.vhdl
 lappend ipCachedFiles triangular_rom256x8_sim_netlist.vhdl

 config_ip_cache -add -dcp triangular_rom256x8.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips triangular_rom256x8]
}

rename_ref -prefix_all triangular_rom256x8_

write_checkpoint -force -noxdef triangular_rom256x8.dcp

catch { report_utilization -file triangular_rom256x8_utilization_synth.rpt -pb triangular_rom256x8_utilization_synth.pb }

if { [catch {
  file copy -force D:/Verilogshuzixitongzonghesheji/DDS/DDS.runs/triangular_rom256x8_synth_1/triangular_rom256x8.dcp D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/ip/triangular_rom256x8/triangular_rom256x8.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/ip/triangular_rom256x8/triangular_rom256x8_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/ip/triangular_rom256x8/triangular_rom256x8_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/ip/triangular_rom256x8/triangular_rom256x8_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/ip/triangular_rom256x8/triangular_rom256x8_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force D:/Verilogshuzixitongzonghesheji/DDS/DDS.runs/triangular_rom256x8_synth_1/triangular_rom256x8.dcp D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/ip/triangular_rom256x8/triangular_rom256x8.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force D:/Verilogshuzixitongzonghesheji/DDS/DDS.runs/triangular_rom256x8_synth_1/triangular_rom256x8_stub.v D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/ip/triangular_rom256x8/triangular_rom256x8_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force D:/Verilogshuzixitongzonghesheji/DDS/DDS.runs/triangular_rom256x8_synth_1/triangular_rom256x8_stub.vhdl D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/ip/triangular_rom256x8/triangular_rom256x8_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force D:/Verilogshuzixitongzonghesheji/DDS/DDS.runs/triangular_rom256x8_synth_1/triangular_rom256x8_sim_netlist.v D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/ip/triangular_rom256x8/triangular_rom256x8_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force D:/Verilogshuzixitongzonghesheji/DDS/DDS.runs/triangular_rom256x8_synth_1/triangular_rom256x8_sim_netlist.vhdl D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/ip/triangular_rom256x8/triangular_rom256x8_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir D:/Verilogshuzixitongzonghesheji/DDS/DDS.ip_user_files/ip/triangular_rom256x8]} {
  catch { 
    file copy -force D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/ip/triangular_rom256x8/triangular_rom256x8_stub.v D:/Verilogshuzixitongzonghesheji/DDS/DDS.ip_user_files/ip/triangular_rom256x8
  }
}

if {[file isdir D:/Verilogshuzixitongzonghesheji/DDS/DDS.ip_user_files/ip/triangular_rom256x8]} {
  catch { 
    file copy -force D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/ip/triangular_rom256x8/triangular_rom256x8_stub.vhdl D:/Verilogshuzixitongzonghesheji/DDS/DDS.ip_user_files/ip/triangular_rom256x8
  }
}
