# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Verilogshuzixitongzonghesheji/DDS/DDS.cache/wt [current_project]
set_property parent.project_path D:/Verilogshuzixitongzonghesheji/DDS/DDS.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Verilogshuzixitongzonghesheji/DDS/DDS.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Tools/sine_wave.coe
read_verilog -library xil_defaultlib {
  D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/new/binary_bcd.v
  D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/new/f_div.v
  D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/new/forever_adder.v
  D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/new/ip_rom.v
  D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/new/lilun_f.v
  D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/new/measure_shiji_f.v
  D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/new/show.v
  D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/new/trans_BCD.v
  D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/new/DDS_top.v
}
read_ip -quiet D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/ip/rom_256x8b/rom_256x8b.xci
set_property used_in_implementation false [get_files -all d:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/ip/rom_256x8b/rom_256x8b_ooc.xdc]
set_property is_locked true [get_files D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/ip/rom_256x8b/rom_256x8b.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/constrs_2/new/DDS.xdc
set_property used_in_implementation false [get_files D:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/constrs_2/new/DDS.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top DDS_top -part xc7a35tcsg324-1


write_checkpoint -force -noxdef DDS_top.dcp

catch { report_utilization -file DDS_top_utilization_synth.rpt -pb DDS_top_utilization_synth.pb }
