# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/DDS.xdc

# IP: ip/rom_256x8b/rom_256x8b.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_256x8b || ORIG_REF_NAME==rom_256x8b}]
