# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/ip/sawtooth_256x8b/sawtooth_256x8b.xci
# IP: The module: 'sawtooth_256x8b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/ip/sawtooth_256x8b/sawtooth_256x8b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sawtooth_256x8b'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/ip/sawtooth_256x8b/sawtooth_256x8b.xci
# IP: The module: 'sawtooth_256x8b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Verilogshuzixitongzonghesheji/DDS/DDS.srcs/sources_1/ip/sawtooth_256x8b/sawtooth_256x8b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sawtooth_256x8b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
